# Generated by Django 3.1.1 on 2021-06-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', max_length=100, verbose_name='Название')),
                ('address', models.TextField(default='', max_length=1000, verbose_name='Адрес')),
                ('surface_area', models.IntegerField(blank=True, default=0, verbose_name='Площадь')),
                ('price', models.IntegerField(default=1000000, verbose_name='Цена')),
                ('text', models.TextField(default='', max_length=50000, verbose_name='Задание')),
                ('photo_path', models.CharField(blank=True, default='', max_length=100, verbose_name='Путь до фото')),
            ],
            options={
                'verbose_name': 'Недвижимость',
                'verbose_name_plural': 'Объекты недвижимости',
            },
        ),
    ]
