# Generated by Django 3.1.1 on 2021-06-16 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Вид недвижимости',
                'verbose_name_plural': 'Виды недвижимости',
            },
        ),
        migrations.AddField(
            model_name='estate',
            name='type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estate.estatetype', verbose_name='Тип'),
        ),
    ]
