# Generated by Django 3.1.1 on 2021-06-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0002_auto_20210617_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='address',
            field=models.CharField(default='', max_length=1000, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='price',
            field=models.FloatField(default=1000000, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='surface_area',
            field=models.FloatField(blank=True, default=0, verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='text',
            field=models.TextField(default='', max_length=50000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Название'),
        ),
    ]
