# Generated by Django 3.1.1 on 2021-06-17 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0004_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Галерея', 'verbose_name_plural': 'Галереи'},
        ),
        migrations.RemoveField(
            model_name='estate',
            name='photo_path',
        ),
    ]
